[acpi] iort: Fix CONFIG_IOMMU_API dependency
Message-id: <20170510090120.15052-13-juma@redhat.com>
Patchwork-id: 178115
O-Subject: [PATCH v2 Pegas1.0 BZ1266462 12/13] ACPI/IORT: Fix CONFIG_IOMMU_API dependency
Bugzilla: 1266462
RH-Acked-by: Mark Salter <msalter@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

From: Lorenzo Pieralisi <lorenzo.pieralisi@arm.com>

commit d49f2dedf33b8e7752ec66ac2b3b5bf4d7210943

The IOMMU probe deferral IORT rework had to add code in
iort_iommu_configure() and iort_iommu_xlate() that requires
the IOMMU_API to be selected in order to compile and work.

Stub out the pieces of code that depend on CONFIG_IOMMU_API
to be selected to prevent compilation failures such as:

drivers/acpi/arm64/iort.c: In function 'iort_iommu_xlate':
drivers/acpi/arm64/iort.c:647:22: error: 'struct iommu_fwspec' has no
member named 'ops'

by wrapping the code in static inline functions that provide a NOP
implementation when CONFIG_IOMMU_API is not selected.

Signed-off-by: Lorenzo Pieralisi <lorenzo.pieralisi@arm.com>
Reported-by: Arnd Bergmann <arnd@arndb.de>
Cc: Arnd Bergmann <arnd@arndb.de>
Cc: Will Deacon <will.deacon@arm.com>
Cc: Catalin Marinas <catalin.marinas@arm.com>
Cc: Robin Murphy <robin.murphy@arm.com>
Cc: Joerg Roedel <joro@8bytes.org>
Cc: Sricharan R <sricharan@codeaurora.org>
Signed-off-by: Joerg Roedel <jroedel@suse.de>
Signed-off-by: Jun ma <juma@redhat.com>
Signed-off-by: Herton R. Krzesinski <herton@redhat.com>