[redhat] copy blk-wbt.h and blk-stat.h headers in kernel-devel package
Message-id: <20170413224712.21280-1-herton@redhat.com>
Patchwork-id: 176747
O-Subject: [Pegas 1.0 PATCH] [redhat] copy blk-{wbt, stat}.h headers in kernel-devel package
Bugzilla: 1440236
RH-Acked-by: Jeremy McNicoll <jmcnicol@redhat.com>
RH-Acked-by: Steve Best <sbest@redhat.com>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1440236
Build Info: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=13016299
Tested: used SystemTap test case provided on the bug report

When you install the kernel-devel+kernel-debuginfo-* packages to use systemtap,
you may be able to write scripts to reference trace points even if they are not
present at runtime in the current kernel. This is the case with the wbt:* trace
points, even with CONFIG_BLK_WBT disabled, systemtap sees the trace points
through sources provided in kernel-debuginfo-common-<arch> package. The problem
is, systemtap uses headers/sources from the kernel-devel package to build its
modules, and the set of sources in kernel-debuginfo-common-<arch> are not fully
present in kernel-devel package.

Also since kernel-devel package in RHEL/Pegas doesn't include the complete kernel
source code, we must copy any necessary/used private headers for it, in addition
to the headers in the main include directory. In this case, copy blk-{wbt,stat}.h
headers so wbt:* trace points can be used with systemtap, to prevent the eg. the
error below:

$ cat wbt.stap
probe kernel.trace("wbt:wbt_stat")? { if (pid() == 0) printf("probe hit\n"); }

$ stap -DSTP_NO_OVERLOAD wbt.stap -c "sleep 0.25"
In file included from /tmp/stap2JE6Mo/stap_191a6a6c90bb85541274935c577b3a01_1618_aux_0.c:14:0:
./include/trace/events/wbt.h:8:36: fatal error: ../../../block/blk-wbt.h: No such file or directory
 #include "../../../block/blk-wbt.h"

As a side note, when you do make rpm-pkg in an upstream kernel tree, you end up
with all kernel source files inside the kernel-devel package, so this is
specific to the way we package the files here (we avoid to include the entire
source to save space, however must take care of the specific cases like this).

Signed-off-by: Herton R. Krzesinski <herton@redhat.com>