[scsi] cxlflash: Select IRQ_POLL
Message-id: <20170525095035.17908.31876.sendpatchset@ibm-p7r2-01.lab.bos.redhat.com>
Patchwork-id: 178950
O-Subject: [PATCH PEGAS1.0 BZ1455362] scsi: cxlflash: Select IRQ_POLL
Bugzilla: 1455362
RH-Acked-by: Jeremy McNicoll <jmcnicol@redhat.com>
RH-Acked-by: Scott Wood <swood@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

RHBZ#:
------
https://bugzilla.redhat.com/show_bug.cgi?id=1455362

Description:
------------
The driver now uses IRQ_POLL and needs to select it to avoid the
following build error.

ERROR: ".irq_poll_complete" [drivers/scsi/cxlflash/cxlflash.ko] undefined!
ERROR: ".irq_poll_sched" [drivers/scsi/cxlflash/cxlflash.ko] undefined!
ERROR: ".irq_poll_disable" [drivers/scsi/cxlflash/cxlflash.ko] undefined!
ERROR: ".irq_poll_init" [drivers/scsi/cxlflash/cxlflash.ko] undefined!

Fixes: cba06e6de403 ("scsi: cxlflash: Implement IRQ polling for RRQ processing")
Signed-off-by: Guenter Roeck <linux@roeck-us.net>
Acked-by: Matthew R. Ochs <mrochs@linux.vnet.ibm.com>
Signed-off-by: Martin K. Petersen <martin.petersen@oracle.com>

Brew:
-----
https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=1327168

Upstream:
---------
commit 07cc1ccfb84320582c9ac389a21cd81df82bc123

https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=07cc1ccfb84320582c9ac389a21cd81df82bc123

Test Status:
------------
I did sanity boot testing on one of my power systems (ibm-p8-rhevm-09.lab4) and was also able to load cxlflash.ko module.

----------
Steve Best

Signed-off-by: Herton R. Krzesinski <herton@redhat.com>